### ISSUE TITLE
Chaining filters throws error

### ISSUE THREAD

**Issue by awalias** [supabase/postgrest-js#23]
```javascript
  supabase
    .from('services')
    .filter('infrastructure_id', 'eq', infra_id)
    .filter('status', 'neq', SERVICE_STATUS.COMING_UP)
    .update({ status: status })
    .then(console.log)
    .catch(console.error)
```

throws 
```
[16/03/2020 08:41:45.102] [ERROR]  (node:19027) UnhandledPromiseRejectionWarning: TypeError: Filters["_".concat(...)] is not a function
    at b.filter (/root/infrastructure/monitoring/node_modules/@supabase/postgrest-js/lib/Request.js:1:3249)
    at /root/infrastructure/monitoring/node_modules/@supabase/postgrest-js/lib/Builder.js:1:1017
    at Array.forEach (<anonymous>)
    at addFilters (/root/infrastructure/monitoring/node_modules/@supabase/postgrest-js/lib/Builder.js:1:965)
    at a.update (/root/infrastructure/monitoring/node_modules/@supabase/postgrest-js/lib/Builder.js:1:2663)
    at a.update (/root/infrastructure/monitoring/node_modules/@supabase/supabase-js/lib/Supabase.js:1:3833)
    ...
```

Will create a test to try and reproduce in isolation

**Comment by awalias** [comment]
@dragarcia can you advise

**Comment by dragarcia** [comment]
We do not support the `neq` filter at the moment. The current workaround for this situation would be:
`.not('status', SERVICE_STATUS.COMING_UP)`
instead of 
`filter('status', 'neq', SERVICE_STATUS.COMING_UP)

**Comment by dragarcia** [comment]
Closing this, the filter `neq` and its accompanying funcion `.neq()` now exists.
