### ISSUE TITLE
some filters can't be called pre-select

### ISSUE THREAD

**Issue by awalias** [supabase/postgrest-js#84]
```javascript
  let response = await supabase
      .from('countries')
      .limit(1)
      .select('*')
```
returns
```bash
(node:66330) UnhandledPromiseRejectionWarning: TypeError: supabase.from(...).limit is not a function
    at main (/Users/supabase/Documents/projects/supabase/supabase_upgrade_scripts/test_supabase.js:12:8)
    at Object.<anonymous> (/Users/supabase/Documents/projects/supabase/supabase_upgrade_scripts/test_supabase.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

but

```javascript
  let response = await supabase
      .from('countries')
      .select('*')
      .limit(1)
```

is ok

same for `offset` and `or` but others like `order` are ok

**Comment by soedirgo** [comment]
Found the culprit: supabase-js is relying on its own implementation for `order`, `limit`, filters, etc. if we use them before `select`. Working on a fix 🛠.

**Comment by awalias** [comment]
good find @soedirgo
